# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - weave-combined-app

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'Dockerfile'
      - '.github/workflows/main_weave-combined-app.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: weavecntr-g2btc0dyc4bzbnc4.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B59328316774151B4EF373D52353442 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_517ECD99738947F19E11F0524559D589 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
            VITE_FACEBOOK_APP_ID=${{ secrets.VITE_FACEBOOK_APP_ID }}
          tags: |
            weavecntr-g2btc0dyc4bzbnc4.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B59328316774151B4EF373D52353442 }}/weave-combined:latest
            weavecntr-g2btc0dyc4bzbnc4.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B59328316774151B4EF373D52353442 }}/weave-combined:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E9A0315DEC6E4849B271810D3D0AA451 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7F83E976E120487F8C6EA785400E23D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BAFB69F4B014608A282A7092E50A9C0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'weave-combined-app'
          slot-name: 'Production'
          images: 'weavecntr-g2btc0dyc4bzbnc4.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8B59328316774151B4EF373D52353442 }}/weave-combined:${{ github.sha }}'